### PR TITLE
Nyaho Hospital added

### PR DESCRIPTION
**Pull request by koolamusic**
Just added Nyaho medical center to the data base with information relative to our research. Services, type of insurance, working hours, number of beds. It is important to know that all information here are taken from their website.

### CODE REVIEW

**Comment by koolamusic** [comment]
@audreymengue  I created this PR, you didn't make a pull request, however you were able to push the project to your github account.

**Comment by audreymengue** [comment]
Hi, should I keep adding? I am asking because I still do not get the pull request, I mean how it consists of. Kindly explain if necessary to do it because I have 2 more hospitals to add.

**Comment by koolamusic** [comment]
Sure, feel free to add and create another pull request.

Pull Requests are made on the Github website

**Comment by audreymengue** [comment]
ok cool.

**Comment by audreymengue** [comment]
I have just added The Trust Hospital.

**Comment by koolamusic** [comment]
visit the repo on your profile or visit https://github.com/wecodeafrica/hospitalsghana/pulls to create a pull request

**Comment by audreymengue** [comment]
Ok, so if I understand it well, anytime I am going to make changes all i need to do is to press that button right? I think I did it for the last push

**Comment by koolamusic** [comment]
yes

**Comment by audreymengue** [comment]
Great

**Pull request merged**
